version: '3.8'

services:
  springboot-app:
    image: samuel007/crud:latest
    ports:
      - "8081:8080"
    environment:
      - SERVER_PORT=8081  # Adjust this if needed
    depends_on:
      - mongo
    networks:
      - monitoring

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - monitoring

  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8082:8080"
    depends_on:
      - keycloak-db
    networks:
      - monitoring

  keycloak-db:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - monitoring

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8083:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - monitoring

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.url=jdbc:postgresql://sonarqube-db:5432/sonar
    depends_on:
      - sonarqube-db
    networks:
      - monitoring

  sonarqube-db:
    image: postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    networks:
      - monitoring

  trivy:
    image: aquasec/trivy:latest
    entrypoint: ["trivy"]
    networks:
      - monitoring

  argocd:
    image: argoproj/argocd
    ports:
      - "8084:8080"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus

volumes:
  jenkins_home:

networks:
  monitoring:
