version: '3.8'

services:
  springboot-app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SERVER_PORT=8081  # Ensure this matches the port in application.properties or use this to override it

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - monitoring